package configer

type suppressLogsOption bool

func (opt suppressLogsOption) apply(parser *configParser) {
	parser.suppressLogs = true
}

// WithSupressLogs suppresses the logs generated by creating a new parser.
//
// By default, logs are active.
func WithSupressLogs() suppressLogsOption {
	return suppressLogsOption(true)
}
